// eslint-disable-next-line no-use-before-define
export { addCharToTextArea, keyboardObj };

function addCharToTextArea() {
  const textArea = document.querySelector('textarea');
  textArea.textContent += String.fromCharCode(this.value).toLowerCase();
}

const keyboardObj = [{
  id: 'key->',
  labelEn: '§',
  labelRu: '>',
  labelEnShift: '±',
  labelRuShift: '<',
  keyCode: 190,
},
{
  id: 'key-1',
  labelEn: '1',
  labelRu: '1',
  labelEnShift: '!',
  labelRuShift: '!',
  keyCode: 49,
},
{
  id: 'key-2',
  labelEn: '2',
  labelRu: '2',
  labelEnShift: '@',
  labelRuShift: '@',
  keyCode: 50,
},
{
  id: 'key-3',
  labelEn: '3',
  labelRu: '3',
  labelEnShift: '#',
  labelRuShift: '#',
  keyCode: 51,
},
{
  id: 'key-4',
  labelEn: '4',
  labelRu: '4',
  labelEnShift: '$',
  labelRuShift: '$',
  keyCode: 52,
},
{
  id: 'key-5',
  labelEn: '5',
  labelRu: '5',
  labelEnShift: '%',
  labelRuShift: '%',
  keyCode: 53,
},
{
  id: 'key-6',
  labelEn: '6',
  labelRu: '6',
  labelEnShift: '^',
  labelRuShift: '^',
  keyCode: 54,
},
{
  id: 'key-7',
  labelEn: '7',
  labelRu: '7',
  labelEnShift: '&',
  labelRuShift: '&',
  keyCode: 55,
},
{
  id: 'key-8',
  labelEn: '8',
  labelRu: '8',
  labelEnShift: '*',
  labelRuShift: '*',
  keyCode: 56,
},
{
  id: 'key-9',
  labelEn: '9',
  labelRu: '9',
  labelEnShift: '(',
  labelRuShift: '(',
  keyCode: 57,
},
{
  id: 'key-0',
  labelEn: '0',
  labelRu: '0',
  labelEnShift: ')',
  labelRuShift: ')',
  keyCode: 48,
},
{
  id: 'key--',
  labelEn: '-',
  labelRu: '-',
  labelEnShift: '_',
  labelRuShift: '_',
  keyCode: 189,
},
{
  id: 'key-+',
  labelEn: '=',
  labelRu: '=',
  labelEnShift: '+',
  labelRuShift: '=',
  keyCode: 187,
},
{
  id: 'key-backspace',
  labelEn: 'Backspace',
  labelRu: 'Backspace',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 8,
},
{
  id: 'key-tab',
  labelEn: 'Tab',
  labelRu: 'Tab',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 9,
},
{
  id: 'key-q',
  labelEn: 'q',
  labelRu: 'й',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 81,
},
{
  id: 'key-w',
  labelEn: 'w',
  labelRu: 'ц',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 87,
},
{
  id: 'key-e',
  labelEn: 'e',
  labelRu: 'у',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 69,
},
{
  id: 'key-r',
  labelEn: 'r',
  labelRu: 'е',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 82,
},
{
  id: 'key-t',
  labelEn: 't',
  labelRu: 'е',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 84,
},
{
  id: 'key-y',
  labelEn: 'y',
  labelRu: 'н',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 89,
},
{
  id: 'key-u',
  labelEn: 'u',
  labelRu: 'г',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 85,
},
{
  id: 'key-i',
  labelEn: 'i',
  labelRu: 'ш',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 73,
},
{
  id: 'key-o',
  labelEn: 'o',
  labelRu: 'щ',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 79,
},
{
  id: 'key-p',
  labelEn: 'p',
  labelRu: 'з',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 80,
},
{
  id: 'key-[',
  labelEn: '[',
  labelRu: 'х',
  labelEnShift: '{',
  labelRuShift: null,
  keyCode: 219,
},
{
  id: 'key-]',
  labelEn: ']',
  labelRu: 'ъ',
  labelEnShift: '}',
  labelRuShift: null,
  keyCode: 221,
},
{
  id: 'key-enter',
  labelEn: 'Enter',
  labelRu: 'Enter',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 13,
},
{
  id: 'key-caps',
  labelEn: 'CapsLock',
  labelRu: 'CapsLock',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 20,
},
{
  id: 'key-a',
  labelEn: 'a',
  labelRu: 'ф',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 65,
},
{
  id: 'key-s',
  labelEn: 's',
  labelRu: 'ы',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 83,
},
{
  id: 'key-d',
  labelEn: 'd',
  labelRu: 'в',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 68,
},
{
  id: 'key-f',
  labelEn: 'f',
  labelRu: 'а',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 70,
},
{
  id: 'key-g',
  labelEn: 'g',
  labelRu: 'п',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 71,
},
{
  id: 'key-h',
  labelEn: 'h',
  labelRu: 'р',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 72,
},
{
  id: 'key-j',
  labelEn: 'j',
  labelRu: 'о',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 74,
},
{
  id: 'key-k',
  labelEn: 'k',
  labelRu: 'л',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 75,
},
{
  id: 'key-l',
  labelEn: 'l',
  labelRu: 'д',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 76,
},
{
  id: 'key-;',
  labelEn: ';',
  labelRu: 'ж',
  labelEnShift: ':',
  labelRuShift: null,
  keyCode: 186,
},
{
  id: 'key-\'',
  labelEn: '\'',
  labelRu: 'э',
  labelEnShift: '"',
  labelRuShift: null,
  keyCode: 222,
},
{
  id: 'key-\\',
  labelEn: '\\',
  labelRu: 'ё',
  labelEnShift: '|',
  labelRuShift: null,
  keyCode: 220,
},
{
  id: 'key-shift-left',
  labelEn: 'Shift',
  labelRu: 'Shift',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 16,
},
{
  id: 'key-`',
  labelEn: '`',
  labelRu: ']',
  labelEnShift: '~',
  labelRuShift: '[',
  keyCode: 221,
},
{
  id: 'key-z',
  labelEn: 'z',
  labelRu: 'я',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 90,
},
{
  id: 'key-x',
  labelEn: 'x',
  labelRu: 'ч',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 88,
},
{
  id: 'key-c',
  labelEn: 'c',
  labelRu: 'с',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 67,
},
{
  id: 'key-v',
  labelEn: 'v',
  labelRu: 'м',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 86,
},
{
  id: 'key-b',
  labelEn: 'b',
  labelRu: 'и',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 66,
},
{
  id: 'key-n',
  labelEn: 'n',
  labelRu: 'т',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 78,
},
{
  id: 'key-m',
  labelEn: 'm',
  labelRu: 'ь',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 77,
},
{
  id: 'key-,',
  labelEn: ',',
  labelRu: 'б',
  labelEnShift: '<',
  labelRuShift: null,
  keyCode: 188,
},
{
  id: 'key-.',
  labelEn: '.',
  labelRu: 'ю',
  labelEnShift: '>',
  labelRuShift: null,
  keyCode: 190,
},
{
  id: 'key-/',
  labelEn: '/',
  labelRu: '/',
  labelEnShift: '?',
  labelRuShift: '?',
  keyCode: 191,
},
{
  id: 'key-shift-right',
  labelEn: 'Shift',
  labelRu: 'Shift',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 16,
},
{
  id: 'key-fn',
  labelEn: 'fn',
  labelRu: 'fn',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: null,
},
{
  id: 'key-control-left',
  labelEn: 'Control',
  labelRu: 'Control',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 17,
},
{
  id: 'key-option-left',
  labelEn: 'Option',
  labelRu: 'Option',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 18,
},
{
  id: 'key-command-left',
  labelEn: 'Command',
  labelRu: 'Command',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 91,
},
{
  id: 'key-space',
  labelEn: 'Space',
  labelRu: 'Space',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 32,
},
{
  id: 'key-command-right',
  labelEn: 'Command',
  labelRu: 'Command',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 93,
},
{
  id: 'key-option-right',
  labelEn: 'Option',
  labelRu: 'Option',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 18,
},
{
  id: 'key-arrow-left',
  labelEn: 'left',
  labelRu: 'left',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 37,
},
{
  id: 'key-arrow-up',
  labelEn: 'up',
  labelRu: 'up',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 38,
},
{
  id: 'key-arrow-down',
  labelEn: 'down',
  labelRu: 'down',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 40,
},
{
  id: 'key-arrow-right',
  labelEn: 'right',
  labelRu: 'right',
  labelEnShift: null,
  labelRuShift: null,
  keyCode: 39,
},
];
